workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS'
      when: never
    - if: '$CI_COMMIT_BRANCH'

include:

- project: 'team/appsec/snyk'
  file: '/.snyk.yaml'
- /build/ci/test_api.yml
- /build/ci/build.yml
- /build/ci/push_docker.yml
- /build/ci/iaac.yml
- /build/ci/deploy_aws.yml
- /build/ci/route.yml

stages:
  - test
  - tests_api
  - build
  - push_docker
  - deploy_template
  - deploy
  - redeploy
  - iaac
  - deploy_aws
  - route

default:
  tags:
  - gke-team-k8s

services:
- name: 
  command:

variables:
  APP_PORT: "80"
  APP_FLOW: "npf"
  APP_NAME: "api-simulations"
  PACKAGE_VERSION: "v1"
  CI_DEBUG_TRACE: "true"
  ARTIFACT_NAME: "${APP_NAME}-${CI_PIPELINE_ID}"
  NAMESPACE: menu
  SNYK_ORG: $SNYK_ORG_DIGITAL_FRONT
  SNYK_TOKEN: $SNYK_TOKEN_ORG_DIGITAL_FRONT
  GOLANG_VERSION: "1.21"
  GOLANG_CONFIG_GITLAB: "true"
  GO_IMAGE: 'registry.b2w.io/b2wdigital/appsec/base-images/golang1.21-alpine3'
  DOCKER_HOST: tcp://127.0.0.1:2375
  DOCKER_TLS_CERTDIR: ''
  DOCKER_DRIVER: overlay2
  SEC_CHECK_JOB_TAG: gke-team-k8s




