// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import entity "project-golang/internal/domain/entity"
import mock "github.com/stretchr/testify/mock"
import model "project-golang/internal/domain/model"

// IRepository is an autogenerated mock type for the IRepository type
type IRepository struct {
	mock.Mock
}

// CreatedBorrower provides a mock function with given fields: tom
func (_m *IRepository) CreatedBorrower(tom *entity.Borrower) error {
	ret := _m.Called(tom)

	var r0 error
	if rf, ok := ret.Get(0).(func(*entity.Borrower) error); ok {
		r0 = rf(tom)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreatedSetup provides a mock function with given fields: set
func (_m *IRepository) CreatedSetup(set *entity.Setup) error {
	ret := _m.Called(set)

	var r0 error
	if rf, ok := ret.Get(0).(func(*entity.Setup) error); ok {
		r0 = rf(set)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreatedSimulation provides a mock function with given fields: simu
func (_m *IRepository) CreatedSimulation(simu *entity.Simulation) (*entity.Simulation, error) {
	ret := _m.Called(simu)

	var r0 *entity.Simulation
	if rf, ok := ret.Get(0).(func(*entity.Simulation) *entity.Simulation); ok {
		r0 = rf(simu)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Simulation)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*entity.Simulation) error); ok {
		r1 = rf(simu)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByIdBorrower provides a mock function with given fields: borrwerId
func (_m *IRepository) FindByIdBorrower(borrwerId string) (*entity.Borrower, error) {
	ret := _m.Called(borrwerId)

	var r0 *entity.Borrower
	if rf, ok := ret.Get(0).(func(string) *entity.Borrower); ok {
		r0 = rf(borrwerId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Borrower)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(borrwerId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByIdSetup provides a mock function with given fields: setupId
func (_m *IRepository) FindByIdSetup(setupId string) (*entity.Setup, error) {
	ret := _m.Called(setupId)

	var r0 *entity.Setup
	if rf, ok := ret.Get(0).(func(string) *entity.Setup); ok {
		r0 = rf(setupId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Setup)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(setupId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByIdSimulation provides a mock function with given fields: simulationId
func (_m *IRepository) FindByIdSimulation(simulationId string) (*entity.Simulation, error) {
	ret := _m.Called(simulationId)

	var r0 *entity.Simulation
	if rf, ok := ret.Get(0).(func(string) *entity.Simulation); ok {
		r0 = rf(simulationId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Simulation)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(simulationId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetSimulations provides a mock function with given fields: param
func (_m *IRepository) GetSimulations(param *model.Params) ([]entity.Simulation, error) {
	ret := _m.Called(param)

	var r0 []entity.Simulation
	if rf, ok := ret.Get(0).(func(*model.Params) []entity.Simulation); ok {
		r0 = rf(param)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Simulation)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*model.Params) error); ok {
		r1 = rf(param)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Ping provides a mock function with given fields:
func (_m *IRepository) Ping() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateSetup provides a mock function with given fields: setupId, newSetup
func (_m *IRepository) UpdateSetup(setupId string, newSetup *entity.Setup) error {
	ret := _m.Called(setupId, newSetup)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, *entity.Setup) error); ok {
		r0 = rf(setupId, newSetup)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateSimulationStatus provides a mock function with given fields: simulationId, status
func (_m *IRepository) UpdateSimulationStatus(simulationId string, status string) error {
	ret := _m.Called(simulationId, status)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(simulationId, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
