ignite:
  zerolog:
    level: TRACE
    formatter: TEXT

worker:
  type: "sqs"
  sqs:
    url:  "http://localhost:4566/000000000000/testQueue"
    visibilityTimeout: 30
    sleepTimeout: 10000

provider:
  integration:

