// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import http "net/http"
import mock "github.com/stretchr/testify/mock"

// ISimulationHandler is an autogenerated mock type for the ISimulationHandler type
type ISimulationHandler struct {
	mock.Mock
}

// BorrowerResponseToSimulation provides a mock function with given fields: w, r
func (_m *ISimulationHandler) BorrowerResponseToSimulation(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// CreatedBorrower provides a mock function with given fields: w, r
func (_m *ISimulationHandler) CreatedBorrower(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// CreatedSetup provides a mock function with given fields: w, r
func (_m *ISimulationHandler) CreatedSetup(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// CreatedSimulation provides a mock function with given fields: w, r
func (_m *ISimulationHandler) CreatedSimulation(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// FindByIdBorrower provides a mock function with given fields: w, r
func (_m *ISimulationHandler) FindByIdBorrower(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// FindByIdSetup provides a mock function with given fields: w, r
func (_m *ISimulationHandler) FindByIdSetup(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// FindByIdSimulation provides a mock function with given fields: w, r
func (_m *ISimulationHandler) FindByIdSimulation(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// FindSimulationsByParam provides a mock function with given fields: w, r
func (_m *ISimulationHandler) FindSimulationsByParam(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// GenerateJWTw provides a mock function with given fields: w, r
func (_m *ISimulationHandler) GenerateJWTw(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// HealthCheckHandler provides a mock function with given fields: w, r
func (_m *ISimulationHandler) HealthCheckHandler(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// UpdateSetup provides a mock function with given fields: w, r
func (_m *ISimulationHandler) UpdateSetup(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// UpdateSimulationStatus provides a mock function with given fields: w, r
func (_m *ISimulationHandler) UpdateSimulationStatus(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}
