// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import dto "project-golang/internal/domain/dto"
import mock "github.com/stretchr/testify/mock"

// IApiAntifraude is an autogenerated mock type for the IApiAntifraude type
type IApiAntifraude struct {
	mock.Mock
}

// CheckAntiFraud provides a mock function with given fields: request
func (_m *IApiAntifraude) CheckAntiFraud(request *dto.AntiFraudRequest) (*dto.AntiFraudResponse, error) {
	ret := _m.Called(request)

	var r0 *dto.AntiFraudResponse
	if rf, ok := ret.Get(0).(func(*dto.AntiFraudRequest) *dto.AntiFraudResponse); ok {
		r0 = rf(request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.AntiFraudResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*dto.AntiFraudRequest) error); ok {
		r1 = rf(request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
