// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import model "project-golang/internal/domain/model"

// Processor is an autogenerated mock type for the Processor type
type Processor struct {
	mock.Mock
}

// Process provides a mock function with given fields: updated
func (_m *Processor) Process(updated *model.Model) error {
	ret := _m.Called(updated)

	var r0 error
	if rf, ok := ret.Get(0).(func(*model.Model) error); ok {
		r0 = rf(updated)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
